#
# Copyright (C) 2021-2022 by TeamYukki@Github, < https://github.com/TeamYukki >.
#
# This file is part of < https://github.com/TeamYukki/YukkiMusicBot > project,
# and is released under the "GNU v3.0 License Agreement".
# Please see < https://github.com/TeamYukki/YukkiMusicBot/blob/master/LICENSE >
#
# All rights reserved.


import asyncio

from pyrogram import Client as c

API_ID = input("\nEnter Your API_ID:\n > ")
API_HASH = input("\nEnter Your API_HASH:\n > ")

print("\n\n Enter Phone number when asked.\n\n")

i = c(":memory:", api_id=20632724, api_hash=fcb71f66e685e3ece3c4c36b87ec19de)


async def main():
    await i.start()
    ss = await i.export_session_string()
    xx = f"HERE IS YOUR STRING SESSION, COPY IT, DON'T SHARE!!\n\n`{BQCIaK4pW55LgN0lyfTV-YYqkNxxpEctC-OwpROZdHDmmsfWUD4oiqDIQEa42qmd3xzjlHmBKkn03iPOFv-3zYe6Odxk0uTemukr8di_3U59egulnYven9xPPD6GR-8E3Ow_6MY2RKRw-oVREJjrNgpMxgMVxT27Ii_46yJAg1PFoOHuHkdwYfV0RvPARSU-vpE0Ru-FPUuRnbpHuxYfb3mWmrIYaYYhQelczkpJpCs06WF7UnpkmJ7TPRduCAyAZTxV_mHFjgWt1-KAINjjhcgJS-IwnfMLQQLm5L0E3YwmoAstVrqTH3Wf5wSBeNb3GEl-s20lyRN0HXj2bPoSQva7ah4Q4QA}`\n\nGENERATED BY YUKKI"
    ok = await i.send_message("me", xx)
    print("\nHERE IS YOUR STRING SESSION, COPY IT, DON'T SHARE!!\n")
    print(f"\n{BQCIaK4pW55LgN0lyfTV-YYqkNxxpEctC-OwpROZdHDmmsfWUD4oiqDIQEa42qmd3xzjlHmBKkn03iPOFv-3zYe6Odxk0uTemukr8di_3U59egulnYven9xPPD6GR-8E3Ow_6MY2RKRw-oVREJjrNgpMxgMVxT27Ii_46yJAg1PFoOHuHkdwYfV0RvPARSU-vpE0Ru-FPUuRnbpHuxYfb3mWmrIYaYYhQelczkpJpCs06WF7UnpkmJ7TPRduCAyAZTxV_mHFjgWt1-KAINjjhcgJS-IwnfMLQQLm5L0E3YwmoAstVrqTH3Wf5wSBeNb3GEl-s20lyRN0HXj2bPoSQva7ah4Q4QA}\n") 
    print("\nGENERATED BY YUKKI\n")


asyncio.run(main())
